const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const puppeteer = require('puppeteer');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('topic')
        .setDescription('Generate a topic for discussion based on previous channel messages (AI BASED).'),

    async execute(interaction) {
        await interaction.deferReply({ ephemeral: true });

        async function topic (message) {
            const browser = await puppeteer.launch({ headless: true });
            const page = await browser.newPage();

            await page.goto('https://chat-app-f2d296.zapier.app/');

            const textBoxSelector = 'textarea[aria-label="chatbot-user-prompt"]';
            await page.waitForSelector(textBoxSelector);

            var textInput = `Give me three topics for discussion based on some recent channel messages. Feel free to make the last suggestion have nothing to do with the previous messages.  YOUR TOPIC IDEAS SHOULD NOT BE 100% BASED ON THE MESSAGES-- IF A MESSAGE DOESN'T MAKE SENSE OR FIT ANY CONTEXT, LEAVE IT OUT.: ${messages}`;

            await page.type(textBoxSelector, textInput);
            await page.keyboard.press('Enter');

            await page.waitForSelector('[data-testid="final-bot-response"] p').catch(err => {
                return;
            });

            value = await page.$$eval('[data-testid="final-bot-response"]', async(elements) => {
                return elements.map((element) => element.textContent);
            });

            await browser.close();

            value.shift();
            return value.join('\n\n\n\n');
        }

        var messages = await interaction.channel.messages.fetch({ limit: 10 });
        var content = [];
        await messages.forEach(async message => {
            content.push(`${message.content}`);
        });

        await content.reverse();
        var output = await topic(content.join(', '));

        const embed = new EmbedBuilder()
            .setColor('Blurple')
            .setTitle('Discussion Topic Suggestions')
            .setDescription(output)
            .setTimestamp()
            .setFooter({ text: 'Tpics generated by AI using previous channel messages.'});

        await interaction.editReply({ embeds: [embed] });
    }
}